# Categorical EDA — Student Performance

**Author:** Mehruza Nosirova

This notebook analyzes the **categorical variables** of the cleaned UCI Student Performance dataset (`student-por-clean.csv`, 649 students, 33 columns).

Steps:
1. Identify the categorical variables and group them by type
2. Build a summary table for all categorical variables
3. Value counts (count and percent) for every variable
4. Compare the final grade `G3` across categories
5. Short observations

Note: some numeric columns (`Medu`, `Fedu`, `traveltime`, `studytime`, `famrel`, `freetime`, `goout`, `Dalc`, `Walc`, `health`) are ordinal scales coded as numbers. They are covered in the Numerical EDA, so this notebook focuses on the 17 text-coded categorical variables.

In [1]:
import sys
sys.path.append("..")

import pandas as pd

from my_modules.categorical_eda_module import (
    get_categorical_columns,
    categorical_summary,
    value_counts_table,
    target_by_category,
    category_gap_ranking,
)

In [2]:
df = pd.read_csv("../data/student-por-clean.csv")
df.shape

(649, 33)

## 1. Categorical variables

The dataset has 17 categorical variables. They fall into three groups:
- **Binary yes/no**: support, activities and lifestyle flags
- **Binary with codes**: school, sex, address, family size, parents' cohabitation status
- **Nominal with 3+ categories**: parents' jobs, reason for choosing the school, guardian

In [3]:
cat_cols = get_categorical_columns(df)

binary_yes_no = [c for c in cat_cols if set(df[c].unique()) == {"yes", "no"}]
binary_other = [c for c in cat_cols if df[c].nunique() == 2 and c not in binary_yes_no]
multi_category = [c for c in cat_cols if df[c].nunique() > 2]

print("Number of categorical variables:", len(cat_cols))
print("Binary yes/no:", binary_yes_no)
print("Binary (other codes):", binary_other)
print("3+ categories:", multi_category)

Number of categorical variables: 17
Binary yes/no: ['schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']
Binary (other codes): ['school', 'sex', 'address', 'famsize', 'Pstatus']
3+ categories: ['Mjob', 'Fjob', 'reason', 'guardian']

## 2. Summary table

One row per variable: number of categories, the categories themselves, the most frequent category and its share, and missing values.

In [4]:
summary = categorical_summary(df, cat_cols)
summary

            n_unique  ... missing_pct
variable              ...
school             2  ...         0.0
sex                2  ...         0.0
address            2  ...         0.0
famsize            2  ...         0.0
Pstatus            2  ...         0.0
Mjob               5  ...         0.0
Fjob               5  ...         0.0
reason             4  ...         0.0
guardian           3  ...         0.0
schoolsup          2  ...         0.0
famsup             2  ...         0.0
paid               2  ...         0.0
activities         2  ...         0.0
nursery            2  ...         0.0
higher             2  ...         0.0
internet           2  ...         0.0
romantic           2  ...         0.0

[17 rows x 5 columns]

## 3. Value counts

Count and percent of students in each category.

In [5]:
for col in binary_other + multi_category:
    print(f"=== {col} ===")
    print(value_counts_table(df, col))
    print()

=== school ===
        count  percent
school
GP        423     65.2
MS        226     34.8

=== sex ===
     count  percent
sex
F      383     59.0
M      266     41.0

=== address ===
         count  percent
address
U          452     69.6
R          197     30.4

=== famsize ===
         count  percent
famsize
GT3        457     70.4
LE3        192     29.6

=== Pstatus ===
         count  percent
Pstatus
T          569     87.7
A           80     12.3

=== Mjob ===
          count  percent
Mjob
other       258     39.8
services    136     21.0
at_home     135     20.8
teacher      72     11.1
health       48      7.4

=== Fjob ===
          count  percent
Fjob
other       367     56.5
services    181     27.9
at_home      42      6.5
teacher      36      5.5
health       23      3.5

=== reason ===
            count  percent
reason
course        285     43.9
home          149     23.0
reputation    143     22.0
other          72     11.1

=== guardian ===
          count  percent
guardian
mother      455     70.1
father      153     23.6
other        41      6.3

Yes/no variables are easier to compare side by side, so they are combined into one table showing the share of students who answered **yes**.

In [6]:
yes_share = pd.DataFrame({
    "yes_count": [(df[c] == "yes").sum() for c in binary_yes_no],
    "yes_pct": [round((df[c] == "yes").mean() * 100, 1) for c in binary_yes_no],
}, index=binary_yes_no).sort_values("yes_pct", ascending=False)

yes_share

            yes_count  yes_pct
higher            580     89.4
nursery           521     80.3
internet          498     76.7
famsup            398     61.3
activities        315     48.5
romantic          239     36.8
schoolsup          68     10.5
paid               39      6.0

## 4. Final grade (G3) by category

`G3` is the target variable (final grade, 0–20). For each category we show the number of students, mean and median `G3`, and `fail_pct` — the percent of students with `G3 < 10` (below the passing grade in the Portuguese system).

Overall reference values:

In [7]:
print("Overall mean G3:", round(df["G3"].mean(), 2))
print("Overall median G3:", df["G3"].median())
print("Overall fail % (G3 < 10):", round((df["G3"] < 10).mean() * 100, 1))

Overall mean G3: 11.91
Overall median G3: 12.0
Overall fail % (G3 < 10): 15.4

In [8]:
for col in cat_cols:
    print(f"=== {col} ===")
    print(target_by_category(df, col))
    print()

=== school ===
        count  mean_G3  median_G3  fail_pct
school
GP        423    12.58       13.0       7.6
MS        226    10.65       11.0      30.1

=== sex ===
     count  mean_G3  median_G3  fail_pct
sex
F      383    12.25       12.0      13.1
M      266    11.41       11.0      18.8

=== address ===
         count  mean_G3  median_G3  fail_pct
address
U          452    12.26       12.0      12.4
R          197    11.09       11.0      22.3

=== famsize ===
         count  mean_G3  median_G3  fail_pct
famsize
LE3        192    12.13       12.0      12.5
GT3        457    11.81       12.0      16.6

=== Pstatus ===
         count  mean_G3  median_G3  fail_pct
Pstatus
A           80    11.91       12.0      15.0
T          569    11.91       12.0      15.5

=== Mjob ===
          count  mean_G3  median_G3  fail_pct
Mjob
teacher      72    13.14       13.0       5.6
health       48    13.06       13.0      12.5
services    136    12.15       12.0      14.0
other       258    11.67       12.0      16.3
at_home     135    11.04       11.0      21.5

=== Fjob ===
          count  mean_G3  median_G3  fail_pct
Fjob
teacher      36    13.58       14.0       8.3
health       23    12.57       12.0      13.0
other       367    11.89       12.0      14.7
services    181    11.63       12.0      18.2
at_home      42    11.43       11.0      16.7

=== reason ===
            count  mean_G3  median_G3  fail_pct
reason
reputation    143    12.94       13.0       7.0
home          149    12.18       12.0      11.4
course        285    11.55       11.0      19.3
other          72    10.69       11.0      25.0

=== guardian ===
          count  mean_G3  median_G3  fail_pct
guardian
father      153     12.2       12.0      10.5
mother      455     11.9       12.0      16.5
other        41     10.9       11.0      22.0

=== schoolsup ===
           count  mean_G3  median_G3  fail_pct
schoolsup
no           581    11.98       12.0      15.8
yes           68    11.28       11.0      11.8

=== famsup ===
        count  mean_G3  median_G3  fail_pct
famsup
yes       398    12.06       12.0      14.3
no        251    11.67       12.0      17.1

=== paid ===
      count  mean_G3  median_G3  fail_pct
paid
no      610    11.95       12.0      14.9
yes      39    11.21       12.0      23.1

=== activities ===
            count  mean_G3  median_G3  fail_pct
activities
yes           315    12.10       12.0      13.7
no            334    11.72       11.0      17.1

=== nursery ===
         count  mean_G3  median_G3  fail_pct
nursery
yes        521    11.95       12.0      15.5
no         128    11.72       11.0      14.8

=== higher ===
        count  mean_G3  median_G3  fail_pct
higher
yes       580    12.28       12.0      11.6
no         69     8.80       10.0      47.8

=== internet ===
          count  mean_G3  median_G3  fail_pct
internet
yes         498    12.17       12.0      13.7
no          151    11.03       11.0      21.2

=== romantic ===
          count  mean_G3  median_G3  fail_pct
romantic
no          410    12.13       12.0      13.2
yes         239    11.52       12.0      19.2

### Ranking: which variables show the largest difference in G3?

For every variable, the gap between the category with the highest mean `G3` and the category with the lowest mean `G3`.

In [9]:
gap_table = category_gap_ranking(df, cat_cols)
gap_table

           highest_category  highest_mean_G3  ... lowest_mean_G3   gap
variable                                      ...
higher                  yes            12.28  ...           8.80  3.48
reason           reputation            12.94  ...          10.69  2.25
Fjob                teacher            13.58  ...          11.43  2.15
Mjob                teacher            13.14  ...          11.04  2.09
school                   GP            12.58  ...          10.65  1.93
guardian             father            12.20  ...          10.90  1.30
address                   U            12.26  ...          11.09  1.18
internet                yes            12.17  ...          11.03  1.15
sex                       F            12.25  ...          11.41  0.85
paid                     no            11.95  ...          11.21  0.75
schoolsup                no            11.98  ...          11.28  0.70
romantic                 no            12.13  ...          11.52  0.61
famsup                  yes            12.06  ...          11.67  0.39
activities              yes            12.10  ...          11.72  0.39
famsize                 LE3            12.13  ...          11.81  0.32
nursery                 yes            11.95  ...          11.72  0.23
Pstatus                   A            11.91  ...          11.91  0.01

[17 rows x 5 columns]

## 5. Observations

**Distribution of categories**
- The data is **imbalanced** for several variables: 89–90% of students want higher education (`higher`), do not receive extra school support (`schoolsup`), and 94% do not take paid extra classes (`paid`). Small groups (39–69 students) make comparisons less reliable.
- About two thirds of students attend **Gabriel Pereira (GP)**, 59% are **female**, 70% live in **urban** areas, and 88% have parents living together (`Pstatus = T`).
- `Mjob` and `Fjob` are dominated by the vague category **"other"** (40% and 57%), which limits how much these variables can tell us.
- The **mother** is the guardian for 70% of students. `activities` is the only nearly balanced variable (48.5% yes).
- No missing values in any categorical variable.

**Relationship with the final grade (G3)**
- **`higher`** shows the strongest difference: students who do **not** plan higher education average 8.8 vs 12.3, and 48% of them fail compared with 12% of the others.
- **`school`**: MS students average about 2 points lower than GP students (10.7 vs 12.6) and fail four times as often (30% vs 8%).
- **`Fjob` / `Mjob`**: children of **teachers** have the highest averages (13.6 and 13.1); children of mothers working **at home** have the lowest among mothers' jobs (11.0).
- **`reason`**: students who chose the school for its **reputation** perform best (12.9, 7% fail); those with reason "other" perform worst (10.7, 25% fail).
- `address`, `internet`, `sex`, `romantic` and `guardian` show moderate gaps (≈0.6–1.3 points): urban, internet access, female, not in a relationship → slightly higher grades.
- `Pstatus`, `nursery`, `famsize`, `activities` and `famsup` show almost **no difference** in G3.
- Interesting: students with extra school support (`schoolsup`) or paid classes (`paid`) have slightly **lower** averages — likely because these supports go to students who were already struggling.

These are preliminary, descriptive findings — they show association, not causation. The strongest candidates for further analysis are `higher`, `school`, `Fjob`/`Mjob`, `reason`, `address` and `internet`.